Repository ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e1-proj-web-t8-pmv-ads-2024-1-e1-proj-curriculo-ideal, pull requests merged in 2024-04, with the labels that each got.

#10 Update 02-Especificação do Projeto.md
  documentos/02-Especificação do Projeto.md
Labels: documentation

#13 Adicionando informacoes de 03-Metodologia.md
  documentos/03-Metodologia.md
Labels: documentation

#12 Adicao de bullet em publico alvo em 01-Documentação de Contexto.md
  documentos/01-Documentação de Contexto.md
Labels: documentation

#14 Adicionando 09-Referências Bibliográficas.md
  documentos/09-Referências Bibliográficas.md
Labels: documentation

#15 Subindo imagens do protótipo
  documentos/img/Cadastre_Sua_Candidatura_1.png
  documentos/img/Cadastre_Sua_Candidatura_2.png
  documentos/img/Como_Fazer_Currículo.png
  documentos/img/Crie_Currículo_1.png
  documentos/img/Crie_Currículo_2.png
  documentos/img/Crie_Currículo_3.png
  documentos/img/Crie_Currículo_4.png
  documentos/img/Crie_Currículo_5.png
  documentos/img/Fluxograma.png
  documentos/img/Home_1.png
  documentos/img/Home_2.png
  documentos/img/Página_Erro.png
  documentos/img/SignUp.png
  documentos/img/Tela_de_Login.png
Labels: documentation

#17 Adicionando informacao ao README.md
  README.md
Labels: documentation

#16 Removendo github-pages 03-Metodologia.md
  documentos/03-Metodologia.md
Labels: documentation

#20 adicionando imagens
  documentos/img/Cadastre-sua-candidatura.png
  documentos/img/Cadastre_Sua_Candidatura_1.png
  documentos/img/Cadastre_Sua_Candidatura_2.png
  documentos/img/Como-fazer-curriculo.png
  documentos/img/Como_Fazer_Currículo.png
  documentos/img/Crie_Currículo_1.png
  documentos/img/Crie_Currículo_2.png
  documentos/img/Crie_Currículo_3.png
  documentos/img/Crie_Currículo_4.png
  documentos/img/Crie_Currículo_5.png
  documentos/img/Faca-seu-curriculo-dados.png
  documentos/img/Faca-seu-curriculo-download.png
  documentos/img/Faca-seu-curriculo-escolaridade.png
  documentos/img/Faca-seu-curriculo-escolha template.png
  documentos/img/Faca-seu-curriculo-experiencias.png
  documentos/img/Faca-seu-curriculo-resumo.png
  documentos/img/Fluxograma.png
  documentos/img/Gerencie-suas-candidaturas.png
  documentos/img/Home.png
  documentos/img/Home_1.png
  documentos/img/Home_2.png
  documentos/img/Login.png
  documentos/img/Pagina-de-erro (1).png
  documentos/img/Pagina-de-erro.png
  documentos/img/Página_Erro.png
  documentos/img/Sign up.png
  documentos/img/SignUp.png
  documentos/img/Tela_de_Login.png
  documentos/img/celular-como-fazer.png
  documentos/img/celular-crie-dados.png
  documentos/img/celular-crie-download.png
  documentos/img/celular-crie-escolaridade.png
  documentos/img/celular-crie-escolha-template.png
  documentos/img/celular-crie-experiencias.png
  documentos/img/celular-crie-resumo.png
  documentos/img/celular-home.png
  documentos/img/celular-home1.png
  documentos/img/celular-login.png
  documentos/img/celular-organize-candidatura.png
  documentos/img/celular-organize.png
  documentos/img/celular-sign-up.png
  documentos/img/celular-tela-erro.png
  documentos/img/componentes.png
  documentos/img/user-flow.png
Labels: documentation

#21 Atualizacao 04-Projeto de Interface.md
  documentos/04-Projeto de Interface.md
Labels: documentation

#27 Adicionando arquivo navbar para ser chamado em todos os arquivos
  codigo-fonte/img/128x128.png
  codigo-fonte/navbar.html
Labels: development

#29 Criando html crie seu curriculo
  codigo-fonte/crie-seu-curriculo.html
  codigo-fonte/download-curriculo.html
Labels: development

#43 Codigo chamando as paginas de footer e navbar foi descomentado e ja f…
  codigo-fonte/crie-seu-curriculo.html
  codigo-fonte/download-curriculo.html
Labels: development, HTML

#44 Home html puc
  .vscode/settings.json
  codigo-fonte/img/contrato.png
  codigo-fonte/img/menina.svg
  codigo-fonte/index.html
Labels: development, HTML

#48 Pagina de login - criar pagina e subir imagens
  codigo-fonte/img/login.svg
  codigo-fonte/img/signup.svg
  codigo-fonte/login.html
Labels: development, HTML

#45 Subindo código de gerenciamento de vagas
  codigo-fonte/gerenciar-vagas.html
Labels: development, HTML

#49 criação das suas candidaturas add nav bar e divs
  codigo-fonte/suascandidaturas.html
Labels: development, HTML

#52 Adicionando estilo ao arquivo footer
  codigo-fonte/footer-style.css
  codigo-fonte/footer.html
Labels: development, CSS

#51 Adicionar CSS ao arquivo de navbar
  codigo-fonte/navbar-style.css
  codigo-fonte/navbar.html
Labels: development, CSS

#50 Pagina de erro e imagem da piranha
  codigo-fonte/como-fazer.html
  codigo-fonte/img/Piranha.png
  codigo-fonte/pagina-erro.html
Labels: development, HTML

#47 HTML página como-fazer
  codigo-fonte/como-fazer.html
Labels: development, HTML

#54 Update README.md
  README.md
Labels: documentation

#55 Correcao navbar
  codigo-fonte/navbar.html
Labels: development, HTML

#56 Corrigindo erros ortograficos da Documentacao de Contexto
  documentos/01-Documentação de Contexto.md
Labels: documentation

#57 Corrigindo erros ortograficos da Metodologia
  documentos/03-Metodologia.md
Labels: documentation

#60 Retirada da frase sugerida pela professora em perfis de usuarios
  documentos/02-Especificação do Projeto.md
Labels: documentation

#58 Corrigindo erros ortograficos do Projeto de Interface e mudando o texto nas partes de Prototipo
  documentos/04-Projeto de Interface.md
Labels: documentation

#64 Alteraçoes em Navbar e footer da página Como-fazer
  codigo-fonte/como-fazer.html
Labels: development, HTML

#65 juntando css de navbar e footer e adicionando ao arquivo crie seu cur…
  codigo-fonte/crie-seu-curriculo.html
  codigo-fonte/navbar-footer-style.css
Labels: development, CSS

#67 Atualização do navbar.css para incluir footer na pagina como fazer
  codigo-fonte/como-fazer.html
Labels: development, CSS

#62 codigo de signup
  codigo-fonte/signup.html
Labels: development, HTML

#69 Primeira parte do CSS/Bootstrap Crie Seu Curriculo
  codigo-fonte/.gitignore
  codigo-fonte/crie-seu-curriculo.css
  codigo-fonte/crie-seu-curriculo.html
Labels: development, CSS

#73 Inserindo modal em suascandidaturas.html
  codigo-fonte/css/suascandidaturas-style.css
  codigo-fonte/js/suascandidaturas-scripts.js
  codigo-fonte/suascandidaturas.html
Labels: documentation, HTML

#71 Colocando bootstrap e css no arquivo suascandidaturas.html e inserindo nvbar e footer
  codigo-fonte/suascandidaturas.html
Labels: documentation, HTML

#74 Usando javascript pra avancar e retroceder com o formulario de crie seu curriculo
  codigo-fonte/crie-seu-curriculo.html
  codigo-fonte/crie-seu-curriculo.js
Labels: documentation, JS

#76 Adicionado slide de apresentação
  apresentacao/README.md
Labels: documentation
