Repository ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e1-proj-web-t8-pmv-ads-2024-1-e1-proj-curriculo-ideal, pull requests merged in 2024-06, with the labels that each got.

#115 Funcionalidade básica de download
  codigo-fonte/criar-curriculo/crie-seu-curriculo.html
  codigo-fonte/criar-curriculo/crie-seu-curriculo.js
Labels: development, HTML, JS

#118 Alterando biblioteca JS para criaçao do currículo
  codigo-fonte/criar-curriculo/crie-seu-curriculo.html
  codigo-fonte/criar-curriculo/crie-seu-curriculo.js
Labels: development, JS

#119 adicionando buscar
  codigo-fonte/suas-candidaturas/suas-candidaturas-style.css
  codigo-fonte/suas-candidaturas/suas-candidaturas.html
  codigo-fonte/suas-candidaturas/suas-candidaturas.js
Labels: development, JS

#120 Adicionando visualização de lista em suas candidaturas
  codigo-fonte/suas-candidaturas/suas-candidaturas-style.css
  codigo-fonte/suas-candidaturas/suas-candidaturas.html
  codigo-fonte/suas-candidaturas/suas-candidaturas.js
Labels: development, HTML, CSS, JS

#121 Ajustando grafico como modal a partir de codigo do Pedro
  codigo-fonte/grafico/grafico.css
  codigo-fonte/grafico/grafico.html
  codigo-fonte/suas-candidaturas/suas-candidaturas-style.css
  codigo-fonte/suas-candidaturas/suas-candidaturas.html
  codigo-fonte/suas-candidaturas/suas-candidaturas.js
Labels: bug

#123 funcionalidade de adicionar outra formacao
  codigo-fonte/criar-curriculo/crie-seu-curriculo.html
  codigo-fonte/criar-curriculo/crie-seu-curriculo.js
Labels: development, JS

#124 Ajustando css depois de adicionar formacao experiencia nova
  codigo-fonte/criar-curriculo/crie-seu-curriculo.css
  codigo-fonte/criar-curriculo/crie-seu-curriculo.html
  codigo-fonte/criar-curriculo/crie-seu-curriculo.js
  codigo-fonte/navbar/navbar-footer-style.css
Labels: documentation, CSS

#127 funcionalidade de gráfico
  codigo-fonte/grafico/grafico.js
  codigo-fonte/suas-candidaturas/suas-candidaturas.html
  codigo-fonte/suas-candidaturas/suas-candidaturas.js
Labels: development, JS

#128 Pequenos ajustes html css js
  codigo-fonte/como-fazer/como-fazer.html
  codigo-fonte/criar-curriculo/crie-seu-curriculo.html
  codigo-fonte/erro/pagina-erro.html
  codigo-fonte/home/index.html
  codigo-fonte/login-e-signup/login.html
  codigo-fonte/login-e-signup/login.js
  codigo-fonte/login-e-signup/signup.html
  codigo-fonte/navbar/navbar-footer-style.css
  codigo-fonte/navbar/navbar.js
  codigo-fonte/suas-candidaturas/suas-candidaturas.html
Labels: development, HTML, CSS, JS

#129 Atualizando documentacao
  README.md
  documentos/09-Referências Bibliográficas.md
Labels: documentation

#132 Update 07-Plano de Testes de Software.md
  documentos/07-Plano de Testes de Software.md
Labels: documentation

#133 Ajustando o conteúdo do PDF
  codigo-fonte/criar-curriculo/crie-seu-curriculo.js
Labels: development, JS

#134 Update 08-Registro de Testes de Software.md
  documentos/08-Registro de Testes de Software.md
Labels: documentation

#131 Atualizando os RF's
  documentos/02-Especificação do Projeto.md
Labels: documentation

#130 Testando CT-1
  documentos/08-Registro de Testes de Software.md
Labels: documentation

#135 Subindo vídeos de testes
  documentos/08-Registro de Testes de Software.md
Labels: documentation

#136 atualizando informações sobre o CT01
  documentos/08-Registro de Testes de Software.md
Labels: documentation

#137 Deixando comentários de avaliação dos testes
  documentos/08-Registro de Testes de Software.md
Labels: documentation

#140 Texto aprenda
  codigo-fonte/.gitignore
  codigo-fonte/como-fazer/como-fazer.css
  codigo-fonte/como-fazer/como-fazer.html
Labels: development

#141 Adicionando citation.cff
  citation.cff
Labels: documentation

#142 Atualizando documentação
  README.md
  apresentacao/README.md
  codigo-fonte/README.md
  documentos/03-Metodologia.md
  documentos/04-Projeto de Interface.md
  documentos/07-Plano de Testes de Software.md
Labels: documentation

#143 condicionando organize ao login
  codigo-fonte/login-e-signup/login-signup-style.css
  codigo-fonte/login-e-signup/login.html
  codigo-fonte/login-e-signup/signup.html
  codigo-fonte/suas-candidaturas/suas-candidaturas-style.css
  codigo-fonte/suas-candidaturas/suas-candidaturas.html
  codigo-fonte/suas-candidaturas/suas-candidaturas.js
Labels: HTML, JS

#138 Novo pdf download
  codigo-fonte/.gitignore
  codigo-fonte/criar-curriculo/crie-seu-curriculo.css
  codigo-fonte/criar-curriculo/crie-seu-curriculo.html
  codigo-fonte/criar-curriculo/crie-seu-curriculo.js
  codigo-fonte/package.json
Labels: development, JS

#144 Ajuste geral css
  codigo-fonte/como-fazer/como-fazer.css
  codigo-fonte/como-fazer/como-fazer.js
  codigo-fonte/criar-curriculo/crie-seu-curriculo.css
  codigo-fonte/criar-curriculo/crie-seu-curriculo.html
  codigo-fonte/erro/pagina-erro.html
  codigo-fonte/grafico/grafico.js
  codigo-fonte/login-e-signup/login-signup-style.css
  codigo-fonte/login-e-signup/login.html
  codigo-fonte/login-e-signup/signup.js
  codigo-fonte/suas-candidaturas/suas-candidaturas-style.css
  codigo-fonte/suas-candidaturas/suas-candidaturas.html
Labels: development, CSS

#145 vizualização em lista
  codigo-fonte/suas-candidaturas/suas-candidaturas-style.css
  codigo-fonte/suas-candidaturas/suas-candidaturas.js
Labels: CSS, JS

#148 Colocando CDN no HTML para corrigir hospedagem
  codigo-fonte/criar-curriculo/crie-seu-curriculo.html
Labels: bug

#146 Corrigindo Requisitos Funcionais para representarem oq foi feito
  documentos/02-Especificação do Projeto.md
Labels: documentation

#147 Update do Plano de Testes para refletir o que foi solicitado pela prof.
  documentos/07-Plano de Testes de Software.md
Labels: documentation

#151 ajustes template
  codigo-fonte/criar-curriculo/crie-seu-curriculo.css
  codigo-fonte/criar-curriculo/crie-seu-curriculo.html
  codigo-fonte/img/curriculo-exemplo-1.png
  codigo-fonte/img/curriculo-exemplo-2.png
Labels: CSS
